#!/usr/bin/env node
/**
 * Overwrites src/environments/environment.secrets.ts from env vars.
 * OPENWEATHER_API_KEY is used for local direct OpenWeather calls.
 * With `--allow-missing`, if the var is unset the script exits 0 without writing.
 *
 * Gemini API keys are not written here — use server/api-proxy.mjs + gemini.proxyBaseUrl in production.
 */
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outFile = join(root, 'src/environments/environment.secrets.ts');

const allowMissing = process.argv.includes('--allow-missing');

const openWeatherKey = process.env.OPENWEATHER_API_KEY;
if (!openWeatherKey || !String(openWeatherKey).trim()) {
  if (allowMissing) {
    console.warn(
      'OPENWEATHER_API_KEY is not set; leaving src/environments/environment.secrets.ts unchanged.',
    );
    process.exit(0);
  }
  console.error(
    'OPENWEATHER_API_KEY is not set.\n' +
      'Example: OPENWEATHER_API_KEY=your_key npm run build\n' +
      'Set --allow-missing if you are using the API proxy instead of direct client calls.',
  );
  process.exit(1);
}

const contents = `/* Generated by scripts/generate-secrets.mjs — do not edit or commit */
export const openWeatherApiKey = ${JSON.stringify(String(openWeatherKey).trim())};
`;

writeFileSync(outFile, contents, 'utf8');
console.log('Wrote src/environments/environment.secrets.ts');
