#!/usr/bin/env node
/**
 * Overwrites src/environments/environment.secrets.ts from OPENWEATHER_API_KEY.
 * The repo keeps a committed empty stub for IDE/TypeScript; production builds need this step.
 */
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outFile = join(root, 'src/environments/environment.secrets.ts');

const key = process.env.OPENWEATHER_API_KEY;
if (!key || !String(key).trim()) {
  console.error(
    'OPENWEATHER_API_KEY is not set. It is required for production builds.\n' +
      'Example: OPENWEATHER_API_KEY=your_key npm run build\n' +
      'In CI, add OPENWEATHER_API_KEY as a secret and run this script before ng build.'
  );
  process.exit(1);
}

const contents = `/* Generated by scripts/generate-secrets.mjs — do not edit or commit */
export const openWeatherApiKey = ${JSON.stringify(String(key).trim())};
`;

writeFileSync(outFile, contents, 'utf8');
console.log('Wrote src/environments/environment.secrets.ts');
