#!/usr/bin/env node
/**
 * Overwrites src/environments/environment.secrets.ts from env vars.
 * OPENWEATHER_API_KEY is required for production builds.
 * With `--allow-missing`, if the var is unset the script exits 0 without writing (for `ng serve`
 * when keys are already in environment.secrets.ts).
 * GEMINI_API_KEY is optional (empty string if unset — AI activity tips stay disabled).
 */
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outFile = join(root, 'src/environments/environment.secrets.ts');

const allowMissing = process.argv.includes('--allow-missing');

const openWeatherKey = process.env.OPENWEATHER_API_KEY;
if (!openWeatherKey || !String(openWeatherKey).trim()) {
  if (allowMissing) {
    console.warn(
      'OPENWEATHER_API_KEY is not set; leaving src/environments/environment.secrets.ts unchanged.',
    );
    process.exit(0);
  }
  console.error(
    'OPENWEATHER_API_KEY is not set. It is required for production builds.\n' +
      'Example: OPENWEATHER_API_KEY=your_key npm run build\n' +
      'In CI, add OPENWEATHER_API_KEY as a secret and run this script before ng build.',
  );
  process.exit(1);
}

const geminiRaw = process.env.GEMINI_API_KEY;
const geminiKey = geminiRaw && String(geminiRaw).trim() ? String(geminiRaw).trim() : '';

const contents = `/* Generated by scripts/generate-secrets.mjs — do not edit or commit */
export const openWeatherApiKey = ${JSON.stringify(String(openWeatherKey).trim())};
export const geminiApiKey = ${JSON.stringify(geminiKey)};
`;

writeFileSync(outFile, contents, 'utf8');
console.log('Wrote src/environments/environment.secrets.ts');
